[package]
name = "automation_aptiutde_questions"
version = "0.1.0"
edition = "2021"

[dependencies]
ollama-rs = "0.2.4"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
tokio = { version = "1.43.0", features = ["full"] }
